version: '3.8'

services:
  # Main API service
  api:
    build: .
    container_name: video-search-api
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
      - ./ground_clips_mp4:/app/ground_clips_mp4
      - ./config:/app/config
    environment:
      - WORKERS=4
      - DEVICE=cpu
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    networks:
      - video-search-network

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: video-search-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - video-search-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: video-search-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/static:/usr/share/nginx/html:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - video-search-network

  # Prometheus monitoring (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: video-search-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - video-search-network

  # Grafana dashboard (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: video-search-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - video-search-network

volumes:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  video-search-network:
    driver: bridge
