version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      RAG_CONFIG_PATH: /app/config/pipeline.yaml
    ports:
      - "8080:8080"
    volumes:
      - ../config:/app/config:ro
      - ../data:/app/data
      - ../web/static:/app/web/static:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
  redis:
    image: redis:7
    ports:
      - "6379:6379"
