data:
  root_dir: ground_clips_mp4
  processed_dir: data/processed
  chunk_duration: 2.0
  min_frames: 2
  frame_rate: 2
  batch_size: 4
  default_tenant: tenant1
  stream_prefix: stream

models:
  device: cuda
  precision: fp32
  quantize: false
  clip_model_name: openai/clip-vit-base-patch32
  videomae_model_name: MCG-NJU/videomae-base
  videoswin_model_name: swin_t

codec:
  codebook_id: your_codebook
  model_id: your_model
  enable_motion_estimation: true
  entropy_bottleneck: true
  quantization_bits: 8
  residual_channels: 128
  latent_channels: 256

index:
  faiss_index_path: data/index/faiss.index
  dim: 512
  nlist: 32
  nprobe: 8
  use_gpu: false
  refresh_interval: 3600

api:
  host: 0.0.0.0
  port: 8081
  workers: 4
  query_expansion_top_k: 5
  max_history: 5

security:
  api_keys:
    - changeme
  rate_limit_per_minute: 120
  rate_limit_burst: 40

monitoring:
  prometheus_port: 9090
  enable_tracing: false

logging:
  level: INFO
  json: false
