project:
  name: "RAG Video Search"
  environment: "development"
  default_tenant_id: "tenant_demo"
  default_codebook_id: "cb_v1"
  default_model_id: "video_encoder_v1"

data:
  root_dir: "datasets"
  processed_dir: "data/processed"
  chunk_duration: 4.0
  frame_rate: 2
  min_frames: 8
  batch_size: 4

models:
  device: "cuda"
  precision: "fp16"
  quantize: false
  clip_model_name: "openai/clip-vit-base-patch32"
  videomae_model_name: "MCG-NJU/videomae-base"
  videoswin_model_name: "microsoft/videoswin-base"

codec:
  enable_motion_estimation: true
  entropy_bottleneck: true
  quantization_bits: 8
  residual_channels: 128
  latent_channels: 256

index:
  faiss_index_path: "data/index/faiss.index"
  dim: 1536
  nlist: 1024
  nprobe: 8
  use_gpu: true
  refresh_interval: 3600

api:
  host: "0.0.0.0"
  port: 8080
  workers: 4
  query_expansion_top_k: 5
  max_history: 5

security:
  api_keys:
    - "changeme"
  rate_limit_per_minute: 120
  rate_limit_burst: 40
  redis_url: null

monitoring:
  prometheus_port: 9090
  enable_tracing: false

logging:
  level: "INFO"
  json: true
  file: "logs/app.log"

frontend:
  static_dir: "web/static"
