project:
  name: "RAG Video Search"
  environment: "production"

data:
  root_dir: "ground_clips_mp4"
  processed_dir: "data/processed"
  chunk_duration: 2.0
  frame_rate: 2
  min_frames: 8
  batch_size: 4
  default_tenant: "tenant-default"
  stream_prefix: "stream"

storage:
  chunks_dir: "data/chunks"
  embeddings_dir: "data/embeddings"
  indexes_dir: "data/indexes"

processing:
  chunk_length_sec: 2
  max_workers: 4
  overlap_sec: 0.5

embedding:
  models:
    - name: "openai/clip-vit-base-patch32"
      embedding_dim: 512
      weight: 1.0

neural_codec:
  quality_level: 3
  bitrate_target: 1000000

index:
  metric: "cosine"
  index_type: "flat"
  faiss_index_path: "data/index/faiss.index"

rag:
  retriever:
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    top_k_retrieve: 100
    top_k_rerank: 20
  generator:
    model_name: "microsoft/DialoGPT-medium"
    max_length: 512
    temperature: 0.7
  query_expansion: true

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  cors_origins:
    - "*"
